### ISSUE TITLE
Ignore alphabetical order if longhand TRBL?

### ISSUE THREAD

**Issue by chris-dura** [hudochenkov/stylelint-order#121]
Alphabetical order keeps things very simple, and has a nice "I don't have to think about it" aspect, especially when working on several different projects where maintainers (if given the option) would probably have different opinions on how to group properties with `order/properties-order`.

However, one exception I've found is that ordering longhand properties in TRBL is usually preferred... instead of the alphabetical BLRT (which is certainly more fun to pronounce 😅)

```scss
.foo {
  color: red;
  margin: 0;
  margin-top: 10px;
  margin-right: 10px;
  margin-bottom: 10px;
  margin-left: 10px;
  padding: 0;
}
```
```shell
✖  Expected margin-bottom to come before margin-top       order/properties-alphabetical-order
```

To enable this, it would be great if the `order/properties-alphabetical-order` and `order/properties-order` were not mutually exclusive. Maintaining a list of _all_ CSS properties in the `order/properties-order` config seems unwieldy.

Ideally, `properties-alphabetical-order` could just `ignore` any property that is in the `properties-order` config, since the user obviously is already defining a "custom order" for those, basically.

Or, it's not very DRY, but even just an `ignore` option for `properties-alphabetical-order` would at least allow users to not apply the rule to certain properties (namely, all the TRBLs).

**Comment by lkraav** [comment]
This probably happens because http://support.ecisolutions.com/doc-ddms/help/reportsmenu/ascii_sort_order_chart.htm

`-` has a lower ASCII order than `:`

Same thing happens on filesystems, where you'd probably want `repository.git` to appear before `repository-branch.git`.

`order/properties-alphabetical-order` could somehow allow defining your own character table, however long or short. If default is `-:`, I'd write `:-` in there.

**Comment by hudochenkov** [comment]
I would even remove this rule, because alphabetical order in CSS is against my believes. But many people find it useful.

Alphabetical order will always be alphabetical. Except few exceptions:

1. Shorthands properties. We make sure longhand properties are placed after shorthands. That's why `margin-*` are after `margin`. Here's a [list of all shorthands](https://github.com/hudochenkov/stylelint-order/blob/3cabbecd704672377b553ccf3554e1805d4b42c3/rules/shorthandData.js). But nice guess, @lkraav :)

2. Prefixed version of the prop goes before unprefixed version. E. g. `-webkit-border-radius` before `border-radius`.

These exceptions still keep true alphabetical order, but make sure that CSS doesn't have bugs prevented by these exceptions.

What you're asking, @chris-dura, I can't call an alphabetical order :) For everything else, other than alphabetical order, `properties-order` will solve a problem. It might not be the nicest solution to have a list of all properties. Luckily you need to do it once in a few year, when you use new CSS properties recently adopted by browsers :)

You don't need to come up with the list of all properties yourself. There are [configs (with logical grouping thoug)](https://github.com/hudochenkov/stylelint-order#example-configs), where you can take list of properties. And there is also [`known-css-properties`](https://github.com/known-css/known-css-properties), which might suit your needs best. Don't forget to check that longhand properties are not overridden by shorthand properties. [`declaration-block-no-shorthand-property-overrides`](https://stylelint.io/user-guide/rules/declaration-block-no-shorthand-property-overrides) might help with that.

I'm afraid I can't give a green light to your proposals. Desired order could be achieved with existing functionality.

**Comment by lkraav** [comment]
> Alphabetical order will always be alphabetical. Except few exceptions:
> 
> 1. Shorthands properties. We make sure longhand properties are placed after shorthands. That's why `margin-*` are after `margin`. Here's a [list of all shorthands](https://github.com/hudochenkov/stylelint-order/blob/3cabbecd704672377b553ccf3554e1805d4b42c3/rules/shorthandData.js). But nice guess, @lkraav :)

Wait, but lint error is exactly the opposite to your claim?

`✖  Expected margin-bottom to come before margin-top       order/properties-alphabetical-order`

So which way is it really?

**Comment by lkraav** [comment]
Nevermind, I missed it's vs another longhand, not `margin`. Horizontal scrollbar hid the meaty part!
