### ISSUE TITLE
`properties-order` seems to be ignored when `properties-alphabetical-order` is also set.

### ISSUE THREAD

**Issue by cduivis** [hudochenkov/stylelint-order#191]
I've got the following use case.
I want all properties to be ordered alphabetically except for a few that I want to group together.

```json
"order/order": [
	"dollar-variables",
	"at-variables",
	"less-mixins",
	"custom-properties",
	"declarations",
	"rules",
	"at-rules"
],
"order/properties-alphabetical-order" : true,
"order/properties-order" : [{
	"groupName"  : "margin",
	"properties" : [ "margin", "margin-top", "margin-right", "margin-bottom", "margin-left" ]
},{
	"groupName"  : "padding",
	"properties" : [ "padding", "padding-top", "padding-right", "padding-bottom", "padding-left" ]
}]
```

I would have expected that by default it orders everything alphabetically, while making an exception for the defined properties in the group.

But as shown by the screenshot below that is not what happens:
![image](https://github.com/hudochenkov/stylelint-order/assets/3647813/7b289a76-3ca8-4795-a901-067da1eac611)

**Comment by rjgotten** [comment]
Ooph, that's kind of killing for long-hand properties that fit an intuitively common order, like the clockwise top-right-bottom-left for border, marging, padding, etc.

**Comment by hudochenkov** [comment]
Alphabetical order does group properties, because they start with the same word, e. g. `margin`.

You can't use both `properties-order` and `properties-alphabetical-order`. You have to pick one.

If you still want a mix of both. Then you have to use `properties-order` and provide your own order, where you could sort everything alphabetically, and then group properties however you like.
