### ISSUE TITLE
Do I need to use postcss-sorting if I'm already using stylelint-order?

### ISSUE THREAD

**Issue by jitendravyas** [hudochenkov/stylelint-order#24]
Is there any benefit of using postcss-sorting over stylelint-order with stylelint?

**Comment by hudochenkov** [comment]
stylelint-order only checks if order is incorrect, while postcss-sorting changes the order in stylesheet. If you run postcss-sorting on each commit, I believe, you don't need stylelint-order, because your order will always be correct. But if you run postcss-sorting manually, you might forget to run it and commit with incorrect order. Then you'll see a warning from stylelint-order when you'll run tests.

**Comment by jitendravyas** [comment]
Thanks for replying. I think there is a possibility of any regression if I change order (manually or automatic) I should check all pages website (legacy website) to make sure nothing is breaking.

**Comment by hudochenkov** [comment]
Theoretically there could be regressions, but most likely there won't be any. Check your codebase with [`declaration-block-no-shorthand-property-overrides`](https://stylelint.io/user-guide/rules/declaration-block-no-shorthand-property-overrides/) rule just in case.
