### ISSUE TITLE
Support object literals (style object)

### ISSUE THREAD

**Issue by choyongjoon** [hudochenkov/stylelint-order#99]
[Stylelint supports styles in object literals](https://github.com/stylelint/stylelint/pull/3506) like
 * style component factories
```
      import glamorous from 'glamorous'; // choose any name for the defaut export

      const Component = glamorous.div({ ... });
      const OtherComponent = glamorous('div')({ ... })
```
* JSX inline style attributes
```
      <Div style={{ ... }}/>
```

But stylelint-order is not working with styles in object. Maybe we need to use `postcss-jsx` before `postcss-sorting`.

**Comment by hudochenkov** [comment]
It's already used in stylelint. stylelint parse file and pass PostCSS AST to stylelint-order. I'm not sure it's possible to safely change and order of properties in an object, because it could not have coma after last property. Before:

```js
{
	a: 0,
	c: 2,
	b: 1
}
```

After:

```js
{
	a: 0,
	b: 1
	c: 2,
}
```

I'm not going to explore this field, but I'm open to PRs. This plugin won't have specific logic to handle last comma, even with PR though. Because it's outside the scope of plugin to fix JavaScript syntax.

**Comment by choyongjoon** [comment]
Thanks for kind reply. I understood why it's not a easy. I'll look into it and try to submit a PR.

**Comment by hudochenkov** [comment]
Closing as there is no maintained syntax for object literals anymore.
